# Must be unique in a given SonarQube instance
sonar.projectKey=pragnakalpdev80_booking-chatbot-frontend
sonar.organization=pragnakalpdev80

# --- optional properties ---

# encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Project configuration
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.css,**/tests/**,**/*.test.jsx
sonar.cpd.exclusions=**/main.jsx,**/vite-env.d.ts,**/tests/**,**/*.test.jsx
sonar.coverage.exclusions=src/App.jsx,src/main.jsx,src/setupTests.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
